apiVersion: v1
kind: Service
metadata:
  name: datacollector
  labels:
    app: datacollector
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
spec:
  type: LoadBalancer
  ports:
  - port: 18630
    targetPort: 18630
    name: ui
  selector:
    app: datacollector
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: datacollector
spec:
  serviceName: "datacollector"
  replicas: 1
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-datacollector-data
        image: streamsets/datacollector
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: data
          mountPath: /sdc
          subPath: sdc
        command: ['sh', '-exc', 'ls -l /opt; cp -R /opt/streamsets-datacollector-3.3.0/* /sdc; chown -R 20159 /data /sdc']
      containers:
      - name: datacollector
        image: streamsets/datacollector
        ports:
        - containerPort: 18630
          name: ui
        readinessProbe:
          exec:
            command: ["curl", "127.0.0.1:18630/public-rest/ping"]
        env:
        - name: SDC_DIST
          value: /sdc
        - name: SDC_CONF_PARSER_LIMIT
          value: "5000000"
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: data
          mountPath: /sdc
          subPath: sdc
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

